# Generated by Django 4.2.16 on 2025-12-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(max_length=100, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField()),
                ('entity', models.CharField(default='PT Bank SeaBank Indonesia', max_length=255)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='delivery_orders/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Faulty', 'Faulty'), ('Lost', 'Lost'), ('Retire', 'Retire')], default='Available', max_length=20)),
                ('asset_type', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('finance_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('rfid_uid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('storeroom', models.CharField(default='IT Storage Lt 35', max_length=100)),
                ('asset_owner_name', models.CharField(default='-', max_length=255)),
                ('owner_department', models.CharField(default='-', max_length=255)),
                ('asset_location', models.CharField(default='-', max_length=255)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('finance_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('rfid_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('store_room', models.CharField(default='IT Storage Lt 35', max_length=100)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('asset_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_department', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.deliveryorder')),
            ],
        ),
    ]
