# Generated by Django 4.2.16 on 2026-01-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterasset',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='last_antenna',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenna_port', models.IntegerField(choices=[(1, 'Luar'), (2, 'Dalam')])),
                ('movement_type', models.CharField(choices=[('IN', 'Masuk Area'), ('OUT', 'Keluar Area')], max_length=10)),
                ('rssi', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_logs', to='api.masterasset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
