# Generated by Django 5.2.11 on 2026-04-01 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_masterasset_is_present_masterasset_last_antenna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrower_department', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Sedang Dipinjam'), ('Returned', 'Sudah Dikembalikan'), ('Overdue', 'Lewat Jatuh Tempo')], default='Active', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='api.masterasset')),
            ],
            options={
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
